"""add country_code to organization

Revision ID: 92b4cd0363ef
Revises: 
Create Date: 2025-12-15 01:33:04.019511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b4cd0363ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.add_column('organization', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.alter_column('organization', 'base_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('organization', 'max_users',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('organization', 'max_bookings',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('organization', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('organization_name_key'), 'organization', type_='unique')
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=True)
    op.alter_column('user', 'user_type',
               existing_type=postgresql.ENUM('Agent', 'Employee', 'Admin', name='usertypeenum'),
               type_=sa.Enum('Agent', 'Employee', 'Admin', name='usertypeenum', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('Active', 'Inactive', name='statusenum'),
               type_=sa.Enum('Active', 'Inactive', name='statusenum', native_enum=False, length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'Active'::statusenum"))
    op.alter_column('user', 'plan_status',
               existing_type=postgresql.ENUM('Active', 'Inactive', name='planstatusenum'),
               type_=sa.Enum('Active', 'Inactive', name='planstatusenum', native_enum=False, length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'Active'::planstatusenum"))
    op.alter_column('user', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    
    op.execute("UPDATE organization SET country_code = 'IN' WHERE country_code IS NULL")

    op.alter_column(
        'organization',
        'country_code',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'plan_status',
               existing_type=sa.Enum('Active', 'Inactive', name='planstatusenum', native_enum=False, length=16),
               type_=postgresql.ENUM('Active', 'Inactive', name='planstatusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Active'::planstatusenum"))
    op.alter_column('user', 'status',
               existing_type=sa.Enum('Active', 'Inactive', name='statusenum', native_enum=False, length=16),
               type_=postgresql.ENUM('Active', 'Inactive', name='statusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Active'::statusenum"))
    op.alter_column('user', 'user_type',
               existing_type=sa.Enum('Agent', 'Employee', 'Admin', name='usertypeenum', native_enum=False, length=32),
               type_=postgresql.ENUM('Agent', 'Employee', 'Admin', name='usertypeenum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.create_unique_constraint(op.f('organization_name_key'), 'organization', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('organization', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('organization', 'max_bookings',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organization', 'max_users',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organization', 'base_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_column('organization', 'country_code')
    op.drop_table('country_master')
    # ### end Alembic commands ###
